In [1]:
import os
import numpy as np
import pandas as pd
from scipy import stats
import matplotlib.pyplot as plt
from numpy import NaN
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import glob

import numpy as np
import pandas as pd

from sklearn import preprocessing
from sklearn.model_selection import train_test_split

2023-02-10 10:39:46.993308: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-10 10:39:47.108752: I tensorflow/core/util/port.cc:104] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-02-10 10:39:47.623270: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-02-10 10:39:47.623336: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-02-10 10:39:47.623341: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.

In [2]:
# Saving all .csv files in folder to list.
path = "MachineLearningCVE/"
files = [file for file in glob.glob(path + "**/*.csv", recursive=True)]

In [3]:
[print(f) for f in files]

MachineLearningCVE/Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv
MachineLearningCVE/Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv
MachineLearningCVE/Wednesday-workingHours.pcap_ISCX.csv
MachineLearningCVE/Tuesday-WorkingHours.pcap_ISCX.csv
MachineLearningCVE/Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv
MachineLearningCVE/Friday-WorkingHours-Morning.pcap_ISCX.csv
MachineLearningCVE/Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv
MachineLearningCVE/Monday-WorkingHours.pcap_ISCX.csv

[None, None, None, None, None, None, None, None]

In [4]:
# Reading all the csv files into dataframes and putting thoose DFs to one list.

dataset = [pd.read_csv(f) for f in files]

In [5]:
# shape of the each files

for d in dataset:
    print(d.shape)

(286467, 79)
(288602, 79)
(692703, 79)
(445909, 79)
(225745, 79)
(191033, 79)
(170366, 79)
(529918, 79)

In [6]:
 #comparing the columns of each tables

for i in range(0,len(dataset)):
    if i != len(dataset)-1:
        same_columns = dataset[i].columns == dataset[i+1].columns
        
        if False in same_columns:
            print(i)
            break

same_columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [7]:
 #Combining all tables into one dataset

dataset = pd.concat([d for d in dataset]).drop_duplicates(keep=False)
dataset.reset_index(drop=True, inplace = True)

In [8]:
# Saving combined data

dataset.to_csv("Dataset_work.csv", index=False)

In [9]:
# dataset shape

dataset.shape

(2427193, 79)

In [10]:
# checking the datatypes of each features
#dataset.dtypes
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2427193 entries, 0 to 2427192
Data columns (total 79 columns):
 #   Column                        Dtype
---  ------                        -----
 0    Destination Port             int64
 1    Flow Duration                int64
 2    Total Fwd Packets            int64
 3    Total Backward Packets       int64
 4   Total Length of Fwd Packets   int64
 5    Total Length of Bwd Packets  int64
 6    Fwd Packet Length Max        int64
 7    Fwd Packet Length Min        int64
 8    Fwd Packet Length Mean       float64
 9    Fwd Packet Length Std        float64
 10  Bwd Packet Length Max         int64
 11   Bwd Packet Length Min        int64
 12   Bwd Packet Length Mean       float64
 13   Bwd Packet Length Std        float64
 14  Flow Bytes/s                  float64
 15   Flow Packets/s               float64
 16   Flow IAT Mean                float64
 17   Flow IAT Std                 float64
 18   Flow IAT Max                 int64
 19   Flow IAT Min                 int64
 20  Fwd IAT Total                 int64
 21   Fwd IAT Mean                 float64
 22   Fwd IAT Std                  float64
 23   Fwd IAT Max                  int64
 24   Fwd IAT Min                  int64
 25  Bwd IAT Total                 int64
 26   Bwd IAT Mean                 float64
 27   Bwd IAT Std                  float64
 28   Bwd IAT Max                  int64
 29   Bwd IAT Min                  int64
 30  Fwd PSH Flags                 int64
 31   Bwd PSH Flags                int64
 32   Fwd URG Flags                int64
 33   Bwd URG Flags                int64
 34   Fwd Header Length            int64
 35   Bwd Header Length            int64
 36  Fwd Packets/s                 float64
 37   Bwd Packets/s                float64
 38   Min Packet Length            int64
 39   Max Packet Length            int64
 40   Packet Length Mean           float64
 41   Packet Length Std            float64
 42   Packet Length Variance       float64
 43  FIN Flag Count                int64
 44   SYN Flag Count               int64
 45   RST Flag Count               int64
 46   PSH Flag Count               int64
 47   ACK Flag Count               int64
 48   URG Flag Count               int64
 49   CWE Flag Count               int64
 50   ECE Flag Count               int64
 51   Down/Up Ratio                int64
 52   Average Packet Size          float64
 53   Avg Fwd Segment Size         float64
 54   Avg Bwd Segment Size         float64
 55   Fwd Header Length.1          int64
 56  Fwd Avg Bytes/Bulk            int64
 57   Fwd Avg Packets/Bulk         int64
 58   Fwd Avg Bulk Rate            int64
 59   Bwd Avg Bytes/Bulk           int64
 60   Bwd Avg Packets/Bulk         int64
 61  Bwd Avg Bulk Rate             int64
 62  Subflow Fwd Packets           int64
 63   Subflow Fwd Bytes            int64
 64   Subflow Bwd Packets          int64
 65   Subflow Bwd Bytes            int64
 66  Init_Win_bytes_forward        int64
 67   Init_Win_bytes_backward      int64
 68   act_data_pkt_fwd             int64
 69   min_seg_size_forward         int64
 70  Active Mean                   float64
 71   Active Std                   float64
 72   Active Max                   int64
 73   Active Min                   int64
 74  Idle Mean                     float64
 75   Idle Std                     float64
 76   Idle Max                     int64
 77   Idle Min                     int64
 78   Label                        object
dtypes: float64(24), int64(54), object(1)
memory usage: 1.4+ GB

In [11]:
# actual dataset

dataset.head(10)

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,22,1266342,41,44,2664,6954,456,0,64.975610,109.864573,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
1,22,1319353,41,44,2664,6954,456,0,64.975610,109.864573,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2,22,1303488,41,42,2728,6634,456,0,66.536585,110.129945,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
3,35396,77,1,2,0,0,0,0,0.000000,0.000000,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
4,22,1307239,41,40,2728,6634,456,0,66.536585,110.129945,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
5,60058,82,1,2,0,0,0,0,0.000000,0.000000,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
6,60060,75,1,2,0,0,0,0,0.000000,0.000000,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
7,35398,77,1,2,0,0,0,0,0.000000,0.000000,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
8,52320,2,2,0,2071,0,2065,6,1035.500000,1455.932862,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
9,52320,27701,15,6,18467,24,2920,0,1231.133333,1054.492489,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN

In [12]:
# Removing whitespaces in column names.

col_names = [col.replace(' ', '') for col in dataset.columns]
dataset.columns = col_names
dataset.head()

,DestinationPort,FlowDuration,TotalFwdPackets,TotalBackwardPackets,TotalLengthofFwdPackets,TotalLengthofBwdPackets,FwdPacketLengthMax,FwdPacketLengthMin,FwdPacketLengthMean,FwdPacketLengthStd,...,min_seg_size_forward,ActiveMean,ActiveStd,ActiveMax,ActiveMin,IdleMean,IdleStd,IdleMax,IdleMin,Label
0,22,1266342,41,44,2664,6954,456,0,64.975610,109.864573,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
1,22,1319353,41,44,2664,6954,456,0,64.975610,109.864573,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2,22,1303488,41,42,2728,6634,456,0,66.536585,110.129945,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
3,35396,77,1,2,0,0,0,0,0.000000,0.000000,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
4,22,1307239,41,40,2728,6634,456,0,66.536585,110.129945,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN

In [13]:
# Dataset conatains 15 labels.
#print(dataset[' Label'].unique())
#len(dataset[' Label'].unique())

dataset['Label'].value_counts()

BENIGN                        2036840
DoS Hulk                       171509
DDoS                           128007
PortScan                        57429
DoS GoldenEye                   10279
FTP-Patator                      5481
DoS slowloris                    5289
DoS Slowhttptest                 5176
SSH-Patator                      3071
Bot                              1947
Web Attack � Brute Force         1445
Web Attack � XSS                  652
Infiltration                       36
Web Attack � Sql Injection         21
Heartbleed                         11
Name: Label, dtype: int64

In [14]:
# This next snippet uses regular expressions to replace wierd characters with dunders.

label_names = dataset['Label'].unique()


import re

label_names = [re.sub("[^a-zA-Z ]+", "", l) for l in label_names]
label_names = [re.sub("[\s\s]", '_', l) for l in label_names]
label_names = [lab.replace("__", "_") for lab in label_names]

label_names, len(label_names)

(['BENIGN',
  'PortScan',
  'Infiltration',
  'DoS_slowloris',
  'DoS_Slowhttptest',
  'DoS_Hulk',
  'DoS_GoldenEye',
  'Heartbleed',
  'FTPPatator',
  'SSHPatator',
  'DDoS',
  'Bot',
  'Web_Attack_Brute_Force',
  'Web_Attack_XSS',
  'Web_Attack_Sql_Injection'],
 15)

In [15]:
# Replacing 'Label' column values with new readable values.

labels = dataset['Label'].unique()

for i in range(0,len(label_names)):
    dataset['Label'] = dataset['Label'].replace({labels[i] : label_names[i]})
    
dataset['Label'].unique()

array(['BENIGN', 'PortScan', 'Infiltration', 'DoS_slowloris',
       'DoS_Slowhttptest', 'DoS_Hulk', 'DoS_GoldenEye', 'Heartbleed',
       'FTPPatator', 'SSHPatator', 'DDoS', 'Bot',
       'Web_Attack_Brute_Force', 'Web_Attack_XSS',
       'Web_Attack_Sql_Injection'], dtype=object)

In [16]:
# changing attack labels to their respective attack class
# total 38 different sub-attacks 
def change_label(dataset):
    dataset.Label.replace(['DoS_slowloris','DoS_Slowhttptest','DoS_Hulk','DoS_GoldenEye','DDoS'],'Dos',inplace=True)
    dataset.Label.replace(['Web_Attack_Brute_Force','Web_Attack_XSS', 'Web_Attack_Sql_Injection','Bot'],'Botnet',inplace=True)
    dataset.Label.replace(['Heartbleed','PortScan'],'PortScan',inplace=True)
    dataset.Label.replace(['Infiltration','FTPPatator','SSHPatator'],'Firewall',inplace=True)

In [17]:
# calling change_label() function
change_label(dataset)

In [18]:
# distribution of attack classes
dataset.Label.value_counts()

BENIGN      2036840
Dos          320260
PortScan      57440
Firewall       8588
Botnet         4065
Name: Label, dtype: int64

In [19]:
# checking null values 

dataset.isnull().values.any()

True

In [20]:
 #Checking which column/s contain NULL values.

[col for col in dataset if dataset[col].isnull().values.any()]

['FlowBytes/s']

In [21]:
# Checking how many NULL values it this column contains.

dataset['FlowBytes/s'].isnull().sum()

334

In [22]:
# Removing rows that contain NULL values

dataset.dropna(inplace=True)

In [23]:
dataset.isnull().any().any()

False

In [24]:
# converting string values to float64 

labl = dataset['Label']
dataset = dataset.loc[:, dataset.columns != 'Label'].astype('float64')

In [25]:


# Checking if all values are finite.

np.all(np.isfinite(dataset))

False

In [26]:


# Checking what column/s contain non-finite values.

nonfinite = [col for col in dataset if not np.all(np.isfinite(dataset[col]))]

nonfinite

['FlowBytes/s', 'FlowPackets/s']

In [27]:
# Checking how many non-finite values each column contains.

finite = np.isfinite(dataset['FlowBytes/s']).sum()

dataset.shape[0] - finite

1132

In [28]:
# Replacing infinite values with NaN values.
dataset = dataset.replace([np.inf, -np.inf], np.nan)

In [29]:
np.any(np.isnan(dataset))

True

In [30]:
dataset = dataset.merge(labl, how='outer', left_index=True, right_index=True)

In [31]:
dataset.dropna(inplace=True)

In [32]:
dataset.shape

(2425727, 79)

In [33]:
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler

In [34]:
# selecting numeric attributes columns from data
numeric_col = dataset.select_dtypes(include='number').columns

# using standard scaler for normalizing
std_scaler = StandardScaler()
def normalization(df,col):
  for i in col:
    arr = df[i]
    arr = np.array(arr)
    df[i] = std_scaler.fit_transform(arr.reshape(len(arr),1))
  return df

In [35]:
# calling the normalization() function
dataset = normalization(dataset.copy(),numeric_col)

# data after normalization
dataset.head()

,DestinationPort,FlowDuration,TotalFwdPackets,TotalBackwardPackets,TotalLengthofFwdPackets,TotalLengthofBwdPackets,FwdPacketLengthMax,FwdPacketLengthMin,FwdPacketLengthMean,FwdPacketLengthStd,...,min_seg_size_forward,ActiveMean,ActiveStd,ActiveMax,ActiveMin,IdleMean,IdleStd,IdleMax,IdleMin,Label
0,-0.459864,-0.446539,0.037514,0.029720,0.188070,-0.004867,0.281243,-0.31171,-0.001137,0.097695,...,0.002761,-0.136006,-0.113061,-0.161613,-0.109217,-0.384114,-0.118364,-0.389626,-0.369714,BENIGN
1,-0.459864,-0.445056,0.037514,0.029720,0.188070,-0.004867,0.281243,-0.31171,-0.001137,0.097695,...,0.002761,-0.136006,-0.113061,-0.161613,-0.109217,-0.384114,-0.118364,-0.389626,-0.369714,BENIGN
2,-0.459864,-0.445500,0.037514,0.027864,0.193999,-0.004998,0.281243,-0.31171,0.006706,0.098573,...,0.002761,-0.136006,-0.113061,-0.161613,-0.109217,-0.384114,-0.118364,-0.389626,-0.369714,BENIGN
3,1.378070,-0.481952,-0.011879,-0.009261,-0.058755,-0.007712,-0.311085,-0.31171,-0.327627,-0.265803,...,0.002761,-0.136006,-0.113061,-0.161613,-0.109217,-0.384114,-0.118364,-0.389626,-0.369714,BENIGN
4,-0.459864,-0.445395,0.037514,0.026008,0.193999,-0.004998,0.281243,-0.31171,0.006706,0.098573,...,0.002761,-0.136006,-0.113061,-0.161613,-0.109217,-0.384114,-0.118364,-0.389626,-0.369714,BENIGN

In [36]:
# binary classification ##

In [37]:
# changing attack category

bin_label = pd.DataFrame(dataset.Label.map(lambda x:'BENIGN' if x=='BENIGN' else 'ATTACK'))

In [38]:
bin_data = dataset.copy()
bin_data['Label'] = bin_label

In [39]:
from sklearn.preprocessing import LabelEncoder

LE1 = LabelEncoder()

enc_label = bin_label.apply(LE1.fit_transform)
bin_data['intrusion']= enc_label

In [40]:
LE1.classes_

array(['ATTACK', 'BENIGN'], dtype=object)

In [41]:
bin_data.head()

,DestinationPort,FlowDuration,TotalFwdPackets,TotalBackwardPackets,TotalLengthofFwdPackets,TotalLengthofBwdPackets,FwdPacketLengthMax,FwdPacketLengthMin,FwdPacketLengthMean,FwdPacketLengthStd,...,ActiveMean,ActiveStd,ActiveMax,ActiveMin,IdleMean,IdleStd,IdleMax,IdleMin,Label,intrusion
0,-0.459864,-0.446539,0.037514,0.029720,0.188070,-0.004867,0.281243,-0.31171,-0.001137,0.097695,...,-0.136006,-0.113061,-0.161613,-0.109217,-0.384114,-0.118364,-0.389626,-0.369714,BENIGN,1
1,-0.459864,-0.445056,0.037514,0.029720,0.188070,-0.004867,0.281243,-0.31171,-0.001137,0.097695,...,-0.136006,-0.113061,-0.161613,-0.109217,-0.384114,-0.118364,-0.389626,-0.369714,BENIGN,1
2,-0.459864,-0.445500,0.037514,0.027864,0.193999,-0.004998,0.281243,-0.31171,0.006706,0.098573,...,-0.136006,-0.113061,-0.161613,-0.109217,-0.384114,-0.118364,-0.389626,-0.369714,BENIGN,1
3,1.378070,-0.481952,-0.011879,-0.009261,-0.058755,-0.007712,-0.311085,-0.31171,-0.327627,-0.265803,...,-0.136006,-0.113061,-0.161613,-0.109217,-0.384114,-0.118364,-0.389626,-0.369714,BENIGN,1
4,-0.459864,-0.445395,0.037514,0.026008,0.193999,-0.004998,0.281243,-0.31171,0.006706,0.098573,...,-0.136006,-0.113061,-0.161613,-0.109217,-0.384114,-0.118364,-0.389626,-0.369714,BENIGN,1

In [42]:
# one-hot-encoding for attack label

bin_data = pd.get_dummies(bin_data,columns=['Label'],prefix="",prefix_sep="")
bin_data['Label']= bin_label
bin_data

,DestinationPort,FlowDuration,TotalFwdPackets,TotalBackwardPackets,TotalLengthofFwdPackets,TotalLengthofBwdPackets,FwdPacketLengthMax,FwdPacketLengthMin,FwdPacketLengthMean,FwdPacketLengthStd,...,ActiveMax,ActiveMin,IdleMean,IdleStd,IdleMax,IdleMin,intrusion,ATTACK,BENIGN,Label
0,-0.459864,-0.446539,0.037514,0.029720,0.188070,-0.004867,0.281243,-0.311710,-0.001137,0.097695,...,-0.161613,-0.109217,-0.384114,-0.118364,-0.389626,-0.369714,1,0,1,BENIGN
1,-0.459864,-0.445056,0.037514,0.029720,0.188070,-0.004867,0.281243,-0.311710,-0.001137,0.097695,...,-0.161613,-0.109217,-0.384114,-0.118364,-0.389626,-0.369714,1,0,1,BENIGN
2,-0.459864,-0.445500,0.037514,0.027864,0.193999,-0.004998,0.281243,-0.311710,0.006706,0.098573,...,-0.161613,-0.109217,-0.384114,-0.118364,-0.389626,-0.369714,1,0,1,BENIGN
3,1.378070,-0.481952,-0.011879,-0.009261,-0.058755,-0.007712,-0.311085,-0.311710,-0.327627,-0.265803,...,-0.161613,-0.109217,-0.384114,-0.118364,-0.389626,-0.369714,1,0,1,BENIGN
4,-0.459864,-0.445395,0.037514,0.026008,0.193999,-0.004998,0.281243,-0.311710,0.006706,0.098573,...,-0.161613,-0.109217,-0.384114,-0.118364,-0.389626,-0.369714,1,0,1,BENIGN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2427188,-0.437990,-0.481430,-0.011879,-0.010189,-0.058199,-0.007709,-0.303292,-0.214180,-0.297478,-0.265803,...,-0.161613,-0.109217,-0.384114,-0.118364,-0.389626,-0.369714,1,0,1,BENIGN
2427189,-0.458254,-0.480254,-0.010644,-0.009261,-0.051343,-0.007648,-0.259127,0.338491,-0.126635,-0.265803,...,-0.161613,-0.109217,-0.384114,-0.118364,-0.389626,-0.369714,1,0,1,BENIGN
2427190,-0.458254,-0.481950,-0.010644,-0.009261,-0.052825,-0.007672,-0.269518,0.208451,-0.166833,-0.265803,...,-0.161613,-0.109217,-0.384114,-0.118364,-0.389626,-0.369714,1,0,1,BENIGN
2427191,-0.458254,-0.481950,-0.010644,-0.009261,-0.051343,-0.007653,-0.259127,0.338491,-0.126635,-0.265803,...,-0.161613,-0.109217,-0.384114,-0.118364,-0.389626,-0.369714,1,0,1,BENIGN
2427192,2.261551,-0.481953,-0.011879,-0.010189,-0.058755,-0.007712,-0.311085,-0.311710,-0.327627,-0.265803,...,-0.161613,-0.109217,-0.384114,-0.118364,-0.389626,-0.369714,1,0,1,BENIGN

In [43]:
## feature extraction ##

In [44]:
# final data for binary classification ##

In [45]:
# creating dataframe with only numeric attributes of binary class and encoded label attribute
numeric_col = dataset.select_dtypes(include = 'number').columns

numeric_bin = bin_data[numeric_col]
numeric_bin['intrusion'] = bin_data['intrusion']

/tmp/ipykernel_12361/1352549749.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  numeric_bin['intrusion'] = bin_data['intrusion']

In [46]:
# extracting features which have more than 0.5 correlation (pearson correlation coefficient)

corr=numeric_bin.corr()
corr_y = abs(corr['intrusion'])
highest_corr = corr_y[corr_y >0.5]
highest_corr.sort_values(ascending=True)

FlowIATMax              0.500885
IdleMax                 0.504334
FwdIATStd               0.535535
PacketLengthMean        0.558979
AveragePacketSize       0.560228
PacketLengthVariance    0.566076
MaxPacketLength         0.591496
PacketLengthStd         0.610186
AvgBwdSegmentSize       0.633516
BwdPacketLengthMean     0.633516
BwdPacketLengthMax      0.633537
BwdPacketLengthStd      0.647723
intrusion               1.000000
Name: intrusion, dtype: float64

In [47]:
numeric_bin = bin_data[['IdleMean','FwdIATMax','FlowIATMax','IdleMax','FwdIATStd','PacketLengthMean','AveragePacketSize','PacketLengthVariance',
                        'MaxPacketLength','PacketLengthStd','AvgBwdSegmentSize','BwdPacketLengthMean','BwdPacketLengthMax',
                        'BwdPacketLengthStd']]

In [48]:

bin_data = numeric_bin.join(bin_data[['intrusion','BENIGN','ATTACK','Label']])

In [49]:
bin_data.to_csv("bin_data_balanced.csv")
bin_data

,IdleMean,FwdIATMax,FlowIATMax,IdleMax,FwdIATStd,PacketLengthMean,AveragePacketSize,PacketLengthVariance,MaxPacketLength,PacketLengthStd,AvgBwdSegmentSize,BwdPacketLengthMean,BwdPacketLengthMax,BwdPacketLengthStd,intrusion,BENIGN,ATTACK,Label
0,-0.384114,-0.364229,-0.373482,-0.389626,-0.354241,-0.263780,-0.302984,-0.288482,-0.059322,-0.153466,-0.302706,-0.302706,-0.017186,-0.087856,1,1,0,BENIGN
1,-0.384114,-0.364225,-0.373204,-0.389626,-0.354251,-0.263780,-0.302984,-0.288482,-0.059322,-0.153466,-0.302706,-0.302706,-0.017186,-0.087856,1,1,0,BENIGN
2,-0.384114,-0.364189,-0.373175,-0.389626,-0.354140,-0.264972,-0.304005,-0.287949,-0.059322,-0.150550,-0.302851,-0.302851,-0.017186,-0.080653,1,1,0,BENIGN
3,-0.384114,-0.402284,-0.409829,-0.389626,-0.369694,-0.610245,-0.626015,-0.320999,-0.512639,-0.510858,-0.548920,-0.548920,-0.488839,-0.437239,1,1,0,BENIGN
4,-0.384114,-0.364169,-0.373186,-0.389626,-0.354269,-0.256550,-0.296054,-0.287311,-0.059322,-0.147087,-0.290547,-0.290547,-0.017186,-0.073925,1,1,0,BENIGN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2427188,-0.384114,-0.402284,-0.409113,-0.389626,-0.369694,-0.591658,-0.600322,-0.320999,-0.509853,-0.510858,-0.539573,-0.539573,-0.485940,-0.437239,1,1,0,BENIGN
2427189,-0.384114,-0.402284,-0.407501,-0.389626,-0.369694,-0.439239,-0.429033,-0.320754,-0.476411,-0.479824,-0.427406,-0.427406,-0.451146,-0.437239,1,1,0,BENIGN
2427190,-0.384114,-0.402284,-0.409827,-0.389626,-0.369694,-0.491284,-0.488984,-0.320956,-0.490345,-0.497791,-0.474142,-0.474142,-0.465643,-0.437239,1,1,0,BENIGN
2427191,-0.384114,-0.402284,-0.409825,-0.389626,-0.369694,-0.446674,-0.437597,-0.320825,-0.479198,-0.484724,-0.436753,-0.436753,-0.454045,-0.437239,1,1,0,BENIGN
2427192,-0.384114,-0.402284,-0.409830,-0.389626,-0.369694,-0.610245,-0.626015,-0.320999,-0.512639,-0.510858,-0.548920,-0.548920,-0.488839,-0.437239,1,1,0,BENIGN

In [50]:
# counting the attacks for binary

bin_data['intrusion'].value_counts()

1    2035505
0     390222
Name: intrusion, dtype: int64

In [51]:
# classifier for binary classification dataset

import warnings
warnings.filterwarnings("ignore")


X = bin_data.iloc[:,0:14].to_numpy() # dataset excluding target attribute (encoded, one-hot-encoded,original)
y = bin_data['intrusion'] # target attribute

X_train, X_validation, Y_train, Y_validation = train_test_split(X, y, test_size=0.20, random_state=1)

In [52]:
X_train = preprocessing.scale(X_train)
X_train = preprocessing.normalize(X_train)

In [53]:
X_validation = preprocessing.scale(X_validation)
X_validation = preprocessing.normalize(X_validation)

In [54]:
print(len(X_train), "Training sequences",X_train.shape)
print(len(X_validation), "Validation sequences",X_validation.shape)

1940581 Training sequences (1940581, 14)
485146 Validation sequences (485146, 14)

In [55]:
X_train = np.reshape(X_train,(X_train.shape[0],X_train.shape[1],1))
X_validation = np.reshape(X_validation,(X_validation.shape[0],X_validation.shape[1],1))

In [56]:
X_train.shape

(1940581, 14, 1)

In [60]:
# Using tanh and sigmoid as activation functions

import time

Model = keras.Sequential([

        keras.layers.Conv2D(96,(4,4),input_shape=(X_train.shape[1],X_train.shape[2],1),activation='relu',padding='same'),
        keras.layers.Conv2D(64,(3,3),activation="relu",padding='same'),
        keras.layers.Conv2D(32,(2,2),activation="relu",padding='same'),
        keras.layers.Dropout(0.5),
        keras.layers.Flatten(),
        keras.layers.Dense(512,activation="relu"),
        keras.layers.Dense(128,activation="relu"),
        keras.layers.Dense(32,activation="relu"),
        keras.layers.Dense(2,activation="softmax"),
    
    
    ])

Model.compile(optimizer='adam',loss='sparse_categorical_crossentropy', metrics=['sparse_categorical_accuracy'])
start_time = time.time()
#Training the model
Model.fit(X_train, Y_train, epochs=5, batch_size=64) 
Model.summary()

# Final evaluation of the model
scores = Model.evaluate(X_validation, Y_validation, verbose=0)
delta = time.time()- start_time
print("Accuracy: %.2f%%" % (scores[1]*100))
print("Training time: %.2f sec" % (delta))

Epoch 1/5

2023-02-10 11:17:42.451373: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] layout failed: INVALID_ARGUMENT: Size of values 0 does not match size of permutation 4 @ fanin shape insequential_1/dropout/dropout/SelectV2-2-TransposeNHWCToNCHW-LayoutOptimizer

30322/30322 [==============================] - 271s 9ms/step - loss: 0.0967 - sparse_categorical_accuracy: 0.9628
Epoch 2/5
30322/30322 [==============================] - 266s 9ms/step - loss: 0.0675 - sparse_categorical_accuracy: 0.9727
Epoch 3/5
30322/30322 [==============================] - 265s 9ms/step - loss: 0.0605 - sparse_categorical_accuracy: 0.9766
Epoch 4/5
30322/30322 [==============================] - 265s 9ms/step - loss: 0.0565 - sparse_categorical_accuracy: 0.9789
Epoch 5/5
30322/30322 [==============================] - 264s 9ms/step - loss: 0.0535 - sparse_categorical_accuracy: 0.9807
Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 conv2d_3 (Conv2D)           (None, 14, 1, 96)         1632

 conv2d_4 (Conv2D)           (None, 14, 1, 64)         55360

 conv2d_5 (Conv2D)           (None, 14, 1, 32)         8224

 dropout (Dropout)           (None, 14, 1, 32)         0

 flatten_1 (Flatten)         (None, 448)               0

 dense_4 (Dense)             (None, 512)               229888

 dense_5 (Dense)             (None, 128)               65664

 dense_6 (Dense)             (None, 32)                4128

 dense_7 (Dense)             (None, 2)                 66

=================================================================
Total params: 364,962
Trainable params: 364,962
Non-trainable params: 0
_________________________________________________________________
Accuracy: 98.94%
Training time: 1392.19 sec

In [58]:
from sklearn.metrics import (precision_score, recall_score,f1_score, accuracy_score,mean_squared_error
                             ,mean_absolute_error,roc_auc_score,confusion_matrix)
from sklearn import metrics

In [59]:
y_pred = Model.predict(X_validation, verbose = 0)
# predict crisp classes for test set
yhat_classes = np.argmax(y_pred,axis=1)
# reduce to 1d array
yhat_probs = y_pred[:, 0]

 
# accuracy: (tp + tn) / (p + n)
accuracy = accuracy_score(Y_validation, yhat_classes)
print('Accuracy: %f' % accuracy)
# precision tp / (tp + fp)
precision = precision_score(Y_validation, yhat_classes)
print('Precision: %f' % precision)
# recall: tp / (tp + fn)
recall = recall_score(Y_validation, yhat_classes)
print('Recall: %f' % recall)
# f1: 2 tp / (2 tp + fp + fn)
f1 = f1_score(Y_validation, yhat_classes)
print('F1 score: %f' % f1)


# ROC AUC
auc = roc_auc_score(Y_validation, yhat_probs)
print('ROC AUC: %f' % auc)
# confusion matrix
matrix = confusion_matrix(Y_validation, yhat_classes)
print(matrix)
# false alaram rate
false_alaram_rate = matrix[1,0]/(matrix[1,0]+matrix[0,0])
print('false alaram rate: %f' % false_alaram_rate)

Accuracy: 0.975111
Precision: 0.991336
Recall: 0.978897
F1 score: 0.985077
ROC AUC: 0.003760
[[ 74524   3483]
 [  8592 398547]]
false alaram rate: 0.103374